SHELL := cmd.exe
.SHELLFLAGS := /C

BIN = bin

all: atr atr2imd imd2atr detok

$(BIN):
	if not exist $(BIN) mkdir $(BIN)

atr: atr.c | $(BIN)
	gcc -std=c23 -W -Wall -pedantic -o $(BIN)/$@ atr.c

atr2imd: atr2imd.c | $(BIN)
	gcc -std=c23 -W -Wall -pedantic -o $(BIN)/$@ atr2imd.c

imd2atr: imd2atr.c | $(BIN)
	gcc -std=c23 -W -Wall -pedantic -o $(BIN)/$@ imd2atr.c

detok: detok.c | $(BIN)
	gcc -std=c23 -W -Wall -pedantic -o $(BIN)/$@ detok.c

clean:
	if exist $(BIN) rmdir /s /q $(BIN)
